### ISSUE TITLE
一定要翻墙？

### ISSUE THREAD

**Issue by qzqs** [wwy863399246/WanAndroid#1]
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for androidx.fragment:fragment:1.1.0
Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.1.0/fragment-1.1.0.aar'.
Could not HEAD 'https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.1.0/fragment-1.1.0.aar'.
dl.google.com

**Comment by wwy863399246** [comment]
下载不下来吗，你可以使用阿里镜像试试

**Comment by qzqs** [comment]
可以加我QQ85446450么？ 我用了阿里镜像也不行
