### ISSUE TITLE
提一个优化点

### ISSUE THREAD

**Issue by PiPiCaptain** [wwy863399246/WanAndroid#2]
大神写的项目，认真地学习了一下，感觉不错，谢谢开源。但网络请求的异常，没有做统一的处理、提示，比如服务器报500、404。我觉得可以加上这些处理、提示

**Comment by PiPiCaptain** [comment]
![image](https://user-images.githubusercontent.com/22672329/100850014-27bc1400-34be-11eb-989f-f8f8a09a3404.png)

比如这样子

**Comment by wwy863399246** [comment]
谢谢，其实网络异常处理这块我在ArticleUserCase类中是做了个简单例子的，关于页面状态显示的处理。关于我不做封装的原因是，用户可能并不需要知道这些信息，我只在viewmodel层做用户需要知道的状态分发(包括网络异常的状态)，然后在view层去处理。当然这样封装对开发者更好，不过我一般就看日志去了，也就没考虑那么多。
  if (result.exception is UnknownHostException) {//加载失败 这里可以区分失败原因，设置不同页面状态
                if (currentPage == 0) loadPageStatus.postValue(LoadPageStatus.NoNet)
            } else {
                if (currentPage == 0) loadPageStatus.postValue(LoadPageStatus.Fail)
            }
            listModel?.postValue(
                ListModel(
                    isRefreshSuccess = false,
                    showError = result.exception.message,
                    loadPageStatus = loadPageStatus,
                    isRefresh = isRefresh
                )
            )
这是ArticleUserCase类处理页面状态的代码。针对不同的状态，做不同的处理。前提是产品经理要求的，哈哈

**Comment by PiPiCaptain** [comment]
![image](https://user-images.githubusercontent.com/22672329/100864369-de28f480-34d0-11eb-9801-daddf8ca44d8.png)

嗯嗯，另外我还觉得，在ErrorMessage可以把状态码也返回。因为后端经常会自定义一些状态码，有些状态码是需要前端做处理的。有了状态码返回，就方便了。

**Comment by wwy863399246** [comment]
嗯嗯，针对自己项目的实际情况进行修改，ErrorMessage也是我自己加的。


| |
helloworldwwy
|
|
helloworldwwy@163.com
|
签名由网易邮箱大师定制


在2020年12月2日 19:07，队长好菜啊<notifications@github.com> 写道：

嗯嗯，另外我还觉得，在ErrorMessage可以把状态码也返回。因为后端经常会自定义一些状态码，有些状态码是需要前端做处理的。有了状态码返回，就方便了。
